[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/public:gsoc:welcome_to_summer_of_code_2015" 
  to = "/public/gsoc/welcome_to_summer_of_code_2015" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:command_line_usage" 
  to = "/public/general/command_line_usage" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:anshul_maheshwari_gsoc15" 
  to = "/public/gsoc/anshul_maheshwari_gsoc15" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:welcome_to_summer_of_code_2016" 
  to = "/public/gsoc/welcome_to_summer_of_code_2016" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:olegkisselef_cea_708" 
  to = "/public/gsoc/olegkisselef_cea_708" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:translating_captions" 
  to = "/public/gsoc/translating_captions" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:olegkisselef_qt_gui" 
  to = "/public/gsoc/olegkisselef_qt_gui" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:downloads" 
  to = "/public/general/downloads" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:amazon_aws_deployment" 
  to = "/public/gsoc/amazon_aws_deployment" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ccextractor_regression_testing" 
  to = "/public/gsoc/ccextractor_regression_testing" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2015:nurendra" 
  to = "/public/gsoc/2015/nurendra" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:vasanth" 
  to = "/public/gsoc/2016/vasanth" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_architecture" 
  to = "/public/gsoc/repository_architecture" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2015:willem" 
  to = "/public/gsoc/2015/willem" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:support" 
  to = "/public/general/support" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:how_to_hire_us" 
  to = "/public/general/how_to_hire_us" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:abishek:subtitle_downloader" 
  to = "/public/gsoc/2016/abishek/subtitle_downloader" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:configuration_options" 
  to = "/public/gsoc/configuration_options" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:database_architecture" 
  to = "/public/gsoc/database_architecture" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:win_gui_usage" 
  to = "/public/general/win_gui_usage" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:extract_from_dvd" 
  to = "/public/gsoc/extract_from_dvd" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:working_with_hdhomerun" 
  to = "/public/general/working_with_hdhomerun" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:using_spupng" 
  to = "/public/general/using_spupng" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:http:sourceforge.net_donate_index.php" 
  to = "/public/general/http/sourceforge.net_donate_index.php" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:willem" 
  to = "/public/gsoc/2016/willem" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:rotating_capture_system_with_hdhomerun" 
  to = "/public/general/rotating_capture_system_with_hdhomerun" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_gsoc2015" 
  to = "/public/gsoc/repository_gsoc2015" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:abhishek:projects" 
  to = "/public/gsoc/2016/abhishek/projects" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:timeline" 
  to = "/public/gsoc/timeline" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ccextractor_bug_hunt" 
  to = "/public/gsoc/ccextractor_bug_hunt" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ccextractor_unassigned_tasks_pick_what_like" 
  to = "/public/gsoc/ccextractor_unassigned_tasks_pick_what_like" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ccextractor_tasks" 
  to = "/public/gsoc/ccextractor_tasks" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:subtitle_extractor_technical_docs" 
  to = "/public/gsoc/subtitle_extractor_technical_docs" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:abhinav" 
  to = "/public/gsoc/2016/abhinav" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:shruti" 
  to = "/public/gsoc/2016/shruti" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:rishabh" 
  to = "/public/gsoc/2016/rishabh" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2016:ruslan" 
  to = "/public/gsoc/2016/ruslan" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:dvd_subtitles_technical_documentation_gsoc_16" 
  to = "/public/gsoc/dvd_subtitles_technical_documentation_gsoc_16" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:dv_support_request" 
  to = "/public/gsoc/dv_support_request" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_quick_install" 
  to = "/public/gsoc/repository_quick_install" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_protocol" 
  to = "/public/gsoc/repository_protocol" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_clients" 
  to = "/public/gsoc/repository_clients" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:server_application_structure" 
  to = "/public/gsoc/server_application_structure" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:repository_logs" 
  to = "/public/gsoc/repository_logs" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:gsoc2016" 
  to = "/public/gsoc/gsoc2016" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2016_task_list" 
  to = "/public/codein/google_code-in_2016_task_list" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_summer_of_code_2017" 
  to = "/public/gsoc/ideas_page_for_summer_of_code_2017" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:subtitle_standards_around_the_world" 
  to = "/public/general/subtitle_standards_around_the_world" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:vagrant" 
  to = "/public/general/vagrant" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:tvsamples" 
  to = "/public/general/tvsamples" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:activity_extractor_user_docs" 
  to = "/public/codein/activity_extractor_user_docs" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:activity_extractor_technical_docs" 
  to = "/public/codein/activity_extractor_technical_docs" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:tess_build" 
  to = "/public/general/tess_build" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:about_the_org" 
  to = "/public/general/about_the_org" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:highspeedsync" 
  to = "/public/gsoc/highspeedsync" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:dtmb" 
  to = "/public/gsoc/dtmb" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:interestingbits" 
  to = "/public/gsoc/interestingbits" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:wordbywordsync" 
  to = "/public/gsoc/wordbywordsync" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:pythonbindings" 
  to = "/public/gsoc/pythonbindings" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:integratedgui" 
  to = "/public/gsoc/integratedgui" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:complete708support" 
  to = "/public/gsoc/complete708support" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:realtimecaptionswebsite" 
  to = "/public/gsoc/realtimecaptionswebsite" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:projectnephos" 
  to = "/public/gsoc/projectnephos" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:windowstesting" 
  to = "/public/gsoc/windowstesting" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:coollinkswithsubfs" 
  to = "/public/general/coollinkswithsubfs" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2017:saurabh" 
  to = "/public/gsoc/2017/saurabh" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2017:satyam" 
  to = "/public/gsoc/2017/satyam" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2017:diptanshu" 
  to = "/public/gsoc/2017/diptanshu" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:python_extension_module_technical_documentation_gsoc_17" 
  to = "/public/gsoc/python_extension_module_technical_documentation_gsoc_17" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:python_extension_module_compilation_documentation_gsoc_17" 
  to = "/public/gsoc/python_extension_module_compilation_documentation_gsoc_17" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:welcome_2017" 
  to = "/public/codein/welcome_2017" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2017_code-in_for_designers" 
  to = "/public/codein/google_code-in_2017_code-in_for_designers" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_summer_of_code_2018" 
  to = "/public/gsoc/ideas_page_for_summer_of_code_2018" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:realtimesubtitles" 
  to = "/public/gsoc/realtimesubtitles" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:sampleplatform" 
  to = "/public/gsoc/sampleplatform" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:jokertv" 
  to = "/public/gsoc/jokertv" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ocr" 
  to = "/public/gsoc/ocr" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:livetvooverinternet" 
  to = "/public/gsoc/livetvooverinternet" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:gettingstartedwithourcode" 
  to = "/public/general/gettingstartedwithourcode" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:whatsccextractor" 
  to = "/public/general/whatsccextractor" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2018:aaditya" 
  to = "/public/gsoc/2018/aaditya" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2018:thealphadollar" 
  to = "/public/gsoc/2018/thealphadollar" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2018:achie27" 
  to = "/public/gsoc/2018/achie27" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:gsoc2017:ccaligner_word_by_word_audio_subtitle_synchronisation_saurabh_shrivastava_gsoc_2017" 
  to = "/public/gsoc/gsoc2017/ccaligner_word_by_word_audio_subtitle_synchronisation_saurabh_shrivastava_gsoc_2017" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2018:saurabh" 
  to = "/public/gsoc/2018/saurabh" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:gsoc2017:python_extension_module_for_ccextractor_diptanshu_jamgade_gsoc_2017" 
  to = "/public/gsoc/gsoc2017/python_extension_module_for_ccextractor_diptanshu_jamgade_gsoc_2017" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:gsoc2017:google_summer_of_code_2017_satyam_mittal" 
  to = "/public/gsoc/gsoc2017/google_summer_of_code_2017_satyam_mittal" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2018:satyam" 
  to = "/public/gsoc/2018/satyam" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2018_task_list_sample" 
  to = "/public/codein/google_code-in_2018_task_list_sample" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2018" 
  to = "/public/codein/google_code-in_2018" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_summer_of_code_2019" 
  to = "/public/gsoc/ideas_page_for_summer_of_code_2019" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:google_summer_of_code_2019" 
  to = "/public/gsoc/google_summer_of_code_2019" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:pipot" 
  to = "/public/gsoc/pipot" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:rcloneweb" 
  to = "/public/gsoc/rcloneweb" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:swaglyrics" 
  to = "/public/gsoc/swaglyrics" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:poormanrekognition" 
  to = "/public/gsoc/poormanrekognition" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_season_of_docs_2019" 
  to = "/public/gsoc/ideas_page_for_season_of_docs_2019" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:blog_posts_our_students" 
  to = "/public/blog_posts_our_students" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2019:pymit" 
  to = "/public/gsoc/2019/pymit" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2019:vertexc" 
  to = "/public/gsoc/2019/vertexc" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2019:faizkhan" 
  to = "/public/gsoc/2019/faizkhan" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:2019:sziraqui" 
  to = "/public/gsoc/2019/sziraqui" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:rust_resources:rust" 
  to = "/public/general/rust_resources/rust" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2019:flutter" 
  to = "/public/codein/google_code-in_2019/flutter" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:flutter_resources:flutter" 
  to = "/public/general/flutter_resources/flutter" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_summer_of_code_2020" 
  to = "/public/gsoc/ideas_page_for_summer_of_code_2020" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:misc:interview_preparation" 
  to = "/public/general/misc/interview_preparation" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:misc:useful_linux_tools" 
  to = "/public/general/misc/useful_linux_tools" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:codein:google_code-in_2019:mastermind" 
  to = "/public/codein/google_code-in_2019/mastermind" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:general:misc:vim" 
  to = "/public/general/misc/vim" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:poormanrekognition2" 
  to = "/public/gsoc/poormanrekognition2" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:rokuchannel" 
  to = "/public/gsoc/rokuchannel" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:pythonprofiler" 
  to = "/public/gsoc/pythonprofiler" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ffmpeg-rust" 
  to = "/public/gsoc/ffmpeg-rust" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:votecounter" 
  to = "/public/gsoc/votecounter" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:japanese" 
  to = "/public/gsoc/japanese" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:rule-engine" 
  to = "/public/gsoc/rule-engine" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:poormantextract" 
  to = "/public/gsoc/poormantextract" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:rcloneweb2" 
  to = "/public/gsoc/rcloneweb2" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:mouseless" 
  to = "/public/gsoc/mouseless" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:flutterrutorrent" 
  to = "/public/gsoc/flutterrutorrent" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:cloudtorrent" 
  to = "/public/gsoc/cloudtorrent" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:takehome" 
  to = "/public/gsoc/takehome" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:linuxtuning" 
  to = "/public/gsoc/linuxtuning" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_season_of_docs_2020" 
  to = "/public/gsoc/ideas_page_for_season_of_docs_2020" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ideas_page_for_summer_of_code_2021" 
  to = "/public/gsoc/ideas_page_for_summer_of_code_2021" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:cc_rust_scaffolding" 
  to = "/public/gsoc/cc_rust_scaffolding" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:cc_rust_708" 
  to = "/public/gsoc/cc_rust_708" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:rokuchannel2" 
  to = "/public/gsoc/rokuchannel2" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:flutterrutorrent2" 
  to = "/public/gsoc/flutterrutorrent2" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:cc_rust_608" 
  to = "/public/gsoc/cc_rust_608" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:cc_rust_ocr" 
  to = "/public/gsoc/cc_rust_ocr" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:ccextractor_gui" 
  to = "/public/gsoc/ccextractor_gui" 
  status = 301 
  force = true

[[redirects]]
  from = "/public:gsoc:flutterdeluge" 
  to = "/public/gsoc/flutterdeluge" 
  status = 301 
  force = true
